module.exports = [{
        name: 'Hamburger',
        description: 'bread, beef, cheese, salad, ketchup',
        country: 'USA',
        imgSrc: 'https://pixabay.com/photos/hamburger-burger-barbeque-bbq-beef-1238246/',
        width: '',
        height: '',
    },
    {
        name: 'Pizza',
        description: 'dough, tomato sauce, cheese, olives',
        country: 'Italy',
        imgSrc: 'https://pixabay.com/photos/pizza-italian-pasta-food-cheese-5179939/',
        width: '',
        height: '',
    },
    {
        name: '',
        description: '',
        imgSrc: 'https://pixabay.com/photos/india-food-indian-meal-2731817/',
        country: 'India',
        width: '',
        height: '',
    },
    {
        name: 'Sushi',
        description: '',
        country: 'Japan',
        imgSrc: 'https://pixabay.com/photos/tuna-salmon-japan-seafood-fish-1957234/',
        width: '',
        height: '',
    },
    {
        name: 'Dumplings',
        description: '',
        country: 'Taiwan',
        imgSrc: 'https://pixabay.com/photos/dumpling-taiwan-tasty-2392893/',
        width: '',
        height: '',
    },
    {
        name: 'Paella',
        description: '',
        country: 'Spain',
        imgSrc: 'https://pixabay.com/photos/seafood-paella-paella-seafood-spain-6280045/',
        width: '',
        height: '',
    },
    {
        name: 'Greek Salad',
        description: '',
        country: 'Greece',
        imgSrc: 'https://pixabay.com/photos/food-plate-greek-salad-caprese-3337621/',
        width: '',
        height: '',
    },
    {
        name: 'Fried Pork',
        description: '',
        country: 'Korea',
        imgSrc: 'https://pixabay.com/photos/pork-meat-fried-korean-food-dinner-1582916/',
        width: '',
        height: '',
    },
    {
        name: 'Tacos',
        description: '',
        country: 'Mexico',
        imgSrc: 'https://pixabay.com/photos/nachos-chips-food-mexican-plate-4454941/',
        width: '',
        height: '',
    },
    {
        name: 'Tacos',
        description: '',
        country: 'Mexico',
        imgSrc: 'https://pixabay.com/photos/nachos-chips-food-mexican-plate-4454941/',
        width: '',
        height: '',
    },
    {
        name: 'Feijoada',
        description: '',
        country: 'Brazil',
        imgSrc: 'https://pixabay.com/photos/bean-stew-black-beans-beans-bacon-5181831/',
        width: '',
        height: '',
    },
]