module.exports = [{
        name: 'Hamburger',
        description: 'bread, beef, cheese, salad, ketchup',
        country: 'USA',
        imgSrc: 'https://pixabay.com/photos/hamburger-burger-barbeque-bbq-beef-1238246/',
        width: '300',
        height: '300',
        cost: '9.99',
    },
    {
        name: 'Pizza',
        description: 'dough, tomato sauce, cheese, olives',
        country: 'Italy',
        imgSrc: 'https://pixabay.com/photos/pizza-italian-pasta-food-cheese-5179939/',
        width: '300',
        height: '300',
        cost: '9.99',
    },
    {
        name: 'Tandoori',
        description: 'meats, breads and vegetables',
        imgSrc: 'https://pixabay.com/photos/india-food-indian-meal-2731817/',
        country: 'India',
        width: '300',
        height: '300',
        cost: '9.99',
    },
    {
        name: 'Sushi',
        description: 'vinegared rice, seafood and vegetables',
        country: 'Japan',
        imgSrc: 'https://pixabay.com/photos/tuna-salmon-japan-seafood-fish-1957234/',
        width: '300',
        height: '300',
        cost: '9.99',
    },
    {
        name: 'Dumplings',
        description: 'flour, potatoes or bread',
        country: 'Taiwan',
        imgSrc: 'https://pixabay.com/photos/dumpling-taiwan-tasty-2392893/',
        width: '300',
        height: '300',
        cost: '9.99',
    },
    {
        name: 'Paella',
        description: 'white rice, shrimp and saffron',
        country: 'Spain',
        imgSrc: 'https://pixabay.com/photos/seafood-paella-paella-seafood-spain-6280045/',
        width: '300',
        height: '300',
        cost: '9.99',
    },
    {
        name: 'Greek Salad',
        description: 'tomatoes, cucumbers, onions',
        country: 'Greece',
        imgSrc: 'https://pixabay.com/photos/food-plate-greek-salad-caprese-3337621/',
        width: '300',
        height: '300',
        cost: '9.99',
    },
    {
        name: 'Fried Pork',
        description: 'thick pork chops, salt and pepper',
        country: 'Korea',
        imgSrc: 'https://pixabay.com/photos/pork-meat-fried-korean-food-dinner-1582916/',
        width: '300',
        height: '300',
        cost: '9.99',
    },
    {
        name: 'Tacos',
        description: 'flour tortillas, chili powder, skirt steak in pieces',
        country: 'Mexico',
        imgSrc: 'https://pixabay.com/photos/nachos-chips-food-mexican-plate-4454941/',
        width: '300',
        height: '300',
        cost: '9.99',
    },
    {
        name: 'Feijoada',
        description: ' black beans, beacon and sausages ',
        country: 'Brazil',
        imgSrc: 'https://pixabay.com/photos/bean-stew-black-beans-beans-bacon-5181831/',
        width: '300',
        height: '300',
        cost: '9.99',
    },
]